# training
epochs: 1500
decoder_max_step: 3000

random_seed: False

batch_size: 32
learning_rate: 1.0e-3
weight_decay: 1.0e-6
grad_clip_thresh: 1.0

cache_dataset: True
use_cuda_if_available: True

balanced_sampling: False

# vocoder
vocoder_state_path: D:/Arabic-TTS/TTS_EgyptianArabic_Tacotron2/pretrained/hifigan-asc-v1/hifigan-asc.pth
vocoder_config_path: pretrained/hifigan-asc-v1/config.json

